# Generated by Django 4.0.2 on 2022-09-16 15:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('profile_img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
