# Generated by Django 4.0.2 on 2022-09-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_partnersdetails_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.countrynames'),
        ),
    ]
