# Generated by Django 4.0.2 on 2022-09-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_partnersdetails_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnersdetails',
            options={'verbose_name_plural': 'PartnersDetails'},
        ),
    ]
