# Generated by Django 4.0.2 on 2022-09-17 20:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('courseType', models.CharField(max_length=200, null=True)),
                ('courseIntake', models.CharField(max_length=200, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('center', models.CharField(blank=True, max_length=200, null=True)),
                ('fees', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200, null=True)),
                ('courseId', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('name', models.CharField(max_length=200, null=True)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.coursesubject')),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('name', models.CharField(max_length=200, null=True)),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('courses', models.ManyToManyField(null=True, to='core_app.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=200, null=True)),
                ('courseType', models.CharField(max_length=200, null=True)),
                ('courseIntake', models.CharField(max_length=200, null=True)),
                ('center', models.CharField(blank=True, max_length=200, null=True)),
                ('fees', models.CharField(max_length=100, null=True)),
                ('courseName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.coursesubject')),
                ('universityName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.university')),
            ],
        ),
    ]
