# Generated by Django 4.0.2 on 2022-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubject',
            name='courseId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
