# Generated by Django 4.0.2 on 2022-09-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_coursesubject_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='courses',
        ),
        migrations.AlterModelOptions(
            name='courserequirements',
            options={'verbose_name_plural': 'CourseRequirements'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='universities',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='courses',
            name='courseId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='CourseSubject',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
