# Generated by Django 4.0.2 on 2022-09-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_remove_university_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequirements',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_requiremeents', to='core_app.courses'),
        ),
        migrations.AlterField(
            model_name='universities',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='university_courses', to='core_app.Courses'),
        ),
    ]
