# Generated by Django 4.0.2 on 2022-09-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_post_comments_courserequirements_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequirements',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core_app.universities'),
        ),
    ]
