# Generated by Django 4.0.2 on 2022-09-20 22:40

import cloudinary.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_alter_courserequirements_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('University', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('passport', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'StudentAddmission',
            },
        ),
    ]
