# Generated by Django 4.0.2 on 2022-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_studentaddmission_courseintake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddmission',
            name='status',
            field=models.CharField(blank=True, default='Submitted', max_length=200, null=True),
        ),
    ]
