# Generated by Django 4.0.2 on 2022-09-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0010_alter_studentaddmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaddmission',
            name='University',
        ),
        migrations.RemoveField(
            model_name='studentaddmission',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentaddmission',
            name='courseIntake',
        ),
        migrations.RemoveField(
            model_name='studentaddmission',
            name='courseType',
        ),
        migrations.RemoveField(
            model_name='studentaddmission',
            name='status',
        ),
        migrations.AddField(
            model_name='studentaddmission',
            name='agent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_information', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentaddmission',
            name='middleName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200, null=True)),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('course_type', models.CharField(max_length=200, null=True)),
                ('course_intake', models.CharField(max_length=200, null=True)),
                ('fees', models.CharField(max_length=100, null=True)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='course selected', max_length=200, null=True)),
                ('selectionId', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectCourse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CourseSelection',
            },
        ),
    ]
