# Generated by Django 4.0.2 on 2022-09-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_remove_studentaddmission_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseselection',
            name='applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
