# Generated by Django 4.0.2 on 2022-10-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_studentapplication_workexperience_studentpassort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpassort',
            name='Place_of_issue',
        ),
        migrations.AddField(
            model_name='studentpassort',
            name='place_of_issue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
