# Generated by Django 4.0.2 on 2022-10-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_remove_studentpassort_place_of_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaddress',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='studentName',
        ),
        migrations.RemoveField(
            model_name='studentpassort',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='studentpassort',
            name='studentName',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='studentName',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='StudentAddress',
        ),
        migrations.DeleteModel(
            name='StudentPassort',
        ),
        migrations.DeleteModel(
            name='WorkEXperience',
        ),
    ]
