# Generated by Django 4.0.2 on 2022-10-19 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0015_remove_studentaddress_agent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEXperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_before', models.BooleanField(default=False)),
                ('membership', models.CharField(blank=True, max_length=200, null=True)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to=settings.AUTH_USER_MODEL)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='core_app.studentapplication')),
            ],
            options={
                'verbose_name_plural': 'WorkEXperience',
            },
        ),
        migrations.CreateModel(
            name='StudentPassort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_num', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_issue', models.CharField(max_length=200, null=True)),
                ('place_of_birth', models.CharField(max_length=200, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('visa_denial', models.BooleanField(default=False)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passportDetail', to=settings.AUTH_USER_MODEL)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passort', to='core_app.studentapplication')),
            ],
            options={
                'verbose_name_plural': 'StudentPassport',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('street_two', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='core_app.studentapplication')),
            ],
            options={
                'verbose_name_plural': 'StudentAddress',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL)),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to='core_app.studentapplication')),
            ],
            options={
                'verbose_name_plural': 'EmergencyContact',
            },
        ),
    ]
