# Generated by Django 4.0.2 on 2022-11-23 17:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_remove_emergencycontact_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
