# Generated by Django 4.0.2 on 2022-11-26 19:28

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_courses_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityImages', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.universities')),
            ],
            options={
                'verbose_name_plural': 'UniversityImages',
            },
        ),
    ]
