# Generated by Django 4.0.2 on 2022-11-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_universityimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='description1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='description2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='why1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
