# Generated by Django 4.0.2 on 2022-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_universities_description1_universities_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='number_of_students',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='type_of_institution',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='type_of_university',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='year_established',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
