# Generated by Django 4.0.2 on 2022-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_universities_number_of_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='application_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
