# Generated by Django 4.0.2 on 2022-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_universities_application_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='description1',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='description2',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
