# Generated by Django 4.0.2 on 2022-11-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_alter_universities_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='application_fees',
        ),
        migrations.AddField(
            model_name='courses',
            name='application_fees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
