# Generated by Django 4.0.2 on 2022-11-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_remove_universities_application_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courseIntake',
        ),
        migrations.CreateModel(
            name='CourseIntakeDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_openApplicationDate', models.DateField(blank=True, null=True)),
                ('winterDeadline', models.DateField(blank=True, null=True)),
                ('winterStart_term_date', models.DateField(blank=True, null=True)),
                ('winterClose_date', models.DateField(blank=True, null=True)),
                ('summer_openApplicationDate', models.DateField(blank=True, null=True)),
                ('summerDeadline', models.DateField(blank=True, null=True)),
                ('summerStart_term_date', models.DateField(blank=True, null=True)),
                ('summerClose_date', models.DateField(blank=True, null=True)),
                ('University', models.ManyToManyField(blank=True, null=True, related_name='course_date', to='core_app.Universities')),
                ('course', models.ManyToManyField(blank=True, null=True, related_name='course_date', to='core_app.Courses')),
            ],
        ),
    ]
