# Generated by Django 4.0.2 on 2022-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_rename_summerclose_date_courseintakedate_summerdeadlineapplicationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseintakedate',
            name='university',
            field=models.ManyToManyField(blank=True, null=True, related_name='university_course_date', to='core_app.Universities'),
        ),
    ]
