# Generated by Django 4.0.2 on 2022-11-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_alter_courseintakedate_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseintakedate',
            name='university',
        ),
        migrations.AddField(
            model_name='courseintakedate',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_course_date', to='core_app.universities'),
        ),
    ]
