# Generated by Django 4.0.2 on 2022-11-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0030_remove_courseintakedate_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseintakedate',
            name='course',
        ),
        migrations.AddField(
            model_name='courseintakedate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_date', to='core_app.courses'),
        ),
    ]
