# Generated by Django 4.0.2 on 2022-11-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_remove_courseintakedate_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseintakedate',
            name='course',
        ),
        migrations.AddField(
            model_name='courseintakedate',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_date', to='core_app.Courses'),
        ),
    ]
