# Generated by Django 4.0.2 on 2022-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0033_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
