# Generated by Django 4.0.2 on 2022-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0036_scholarship_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='about',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
