# Generated by Django 4.0.2 on 2022-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0037_universities_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='universities',
            old_name='description2',
            new_name='overview',
        ),
    ]
