# Generated by Django 4.0.2 on 2022-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0038_rename_description1_universities_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='about',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='detail',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='overview',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
