# Generated by Django 4.0.2 on 2022-12-04 21:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0040_alter_courses_about_alter_courses_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.universities')),
            ],
            options={
                'verbose_name_plural': 'UniversityImages',
            },
        ),
    ]
