# Generated by Django 4.0.2 on 2022-12-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0042_alter_universityaccommodation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityaccommodation',
            name='detail',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
