# Generated by Django 4.0.2 on 2022-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0043_alter_universityaccommodation_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityaccommodation',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
