# Generated by Django 4.0.2 on 2023-01-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0044_universityaccommodation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequirements',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_requiremeents', to='core_app.courses'),
        ),
    ]
