# Generated by Django 4.0.2 on 2023-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0045_alter_courserequirements_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='university_courses', to='core_app.Courses'),
        ),
    ]
