# Generated by Django 4.0.2 on 2023-01-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0046_alter_universities_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='why1',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='about',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='detail',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='overview',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='about',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='description',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='overview',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='why1',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
