# Generated by Django 4.0.2 on 2023-01-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0047_courses_why1_alter_courses_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseintakedate',
            name='WinterIntakeTime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='courseintakedate',
            name='summerIntakeTime',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
