# Generated by Django 4.0.2 on 2023-01-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0048_courseintakedate_winterintaketime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAddmission',
        ),
    ]
