# Generated by Django 4.0.2 on 2023-01-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0050_studentaddmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPassort',
        ),
    ]
