# Generated by Django 4.0.2 on 2023-01-23 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0051_delete_studentpassort'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPassort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('passport_num', models.CharField(max_length=200)),
                ('place_of_issue', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('visa_denial', models.BooleanField(default=False)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passportDetail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Passport',
            },
        ),
    ]
