# Generated by Django 4.0.2 on 2023-01-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0052_studentpassort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAddmission',
        ),
    ]
