# Generated by Django 4.0.2 on 2023-01-23 17:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0053_delete_studentaddmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('middleName', models.CharField(blank=True, max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('application_date', models.DateField(blank=True, null=True)),
                ('passport', cloudinary.models.CloudinaryField(max_length=255)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=200)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Addmission',
            },
        ),
    ]
