# Generated by Django 4.0.2 on 2023-01-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0054_studentaddmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSelection',
        ),
    ]
