# Generated by Django 4.0.2 on 2023-01-23 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0055_delete_courseselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200, null=True)),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('course_type', models.CharField(max_length=200, null=True)),
                ('course_intake', models.CharField(max_length=200, null=True)),
                ('fees', models.CharField(max_length=100, null=True)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='course selected', max_length=200, null=True)),
                ('selectionId', models.CharField(blank=True, max_length=200, null=True)),
                ('applied', models.BooleanField(blank=True, default=False, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectCourse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CourseSelection',
            },
        ),
    ]
