# Generated by Django 4.0.2 on 2023-01-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0056_courseselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseselection',
            old_name='email',
            new_name='studentEmail',
        ),
    ]
