# Generated by Django 4.0.2 on 2023-01-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0057_rename_email_courseselection_studentemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAddress',
        ),
    ]
