# Generated by Django 4.0.2 on 2023-01-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0061_workexperience_emergencycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='agent_name',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='WorkEXperience',
        ),
    ]
