# Generated by Django 4.0.2 on 2023-02-05 00:38

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0064_alter_courserequirements_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('sch_attended', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('certificate', models.CharField(max_length=200)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Academic Qualification',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.schoolqualification')),
            ],
        ),
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('academics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.schoolqualification')),
            ],
        ),
    ]
