# Generated by Django 4.0.2 on 2023-02-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0065_schoolqualification_variants_resultimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
