# Generated by Django 4.0.2 on 2023-02-09 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0066_delete_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sch_attended', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('certificate_obtained', models.CharField(max_length=200)),
                ('agent_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_qualifications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.schoolqualification')),
            ],
        ),
    ]
