# Generated by Django 4.0.2 on 2023-02-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0067_additionalqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalqualification',
            name='price',
        ),
        migrations.RemoveField(
            model_name='additionalqualification',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='additionalqualification',
            name='size',
        ),
    ]
