# Generated by Django 4.0.2 on 2023-02-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0069_resultimage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultimage',
            old_name='image',
            new_name='document',
        ),
    ]
