# Generated by Django 4.0.2 on 2023-02-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0070_rename_image_resultimage_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultimage',
            old_name='description',
            new_name='title',
        ),
    ]
