# Generated by Django 4.0.2 on 2023-02-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0071_rename_description_resultimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolqualification',
            name='agent_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicsQualifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
