# Generated by Django 4.0.2 on 2023-02-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0072_alter_schoolqualification_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalqualification',
            name='agent_name',
        ),
    ]
